accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.login_user, name='login'),
    path('logout', views.log_out, name='logout'),
    path('register_owner', views.register_property_owner_user, name='register_property_owner_user'),
    path('register_contractor', views.register_contractor_user, name='register_contractor_user'),
    path('profile', views.profile, name='profile'),
    path('smithjones', views.smithjones, name='smithjones'),
]

adu_hack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('contractorPage/', TemplateView.as_view(template_name='index2.html'), name='index2'),
    path('accounts/', include('accounts.urls')),
    path('connections/', include('connections.urls')),
]

connections/urls.py
from django.urls import path
from . import views

app_name = 'connections'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('searchCont/', views.searchTwo, name='searchTwo'),
    # path('results/', views.results, name='results'),
    # path('profile/', views.profile, name='profile'),
]

templates/partials/_navbar.html
{% load static %}
<nav>
    <a href="{% url 'index' %}"><img class="logo" src="{% static 'imgs/logo.svg' %}"></a>
    <ul>
        {% if user.is_authenticated %}
            <li>Welcome <a href="#">{{ user.name }}</a></li>
            <li><a href="{% url 'connections:search' %}">Search</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        <li><a href="{% url 'accounts:register_property_owner_user' %}">Register Property User</a></li>
        {% endif %}

    </ul>
</nav>