accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.login_user, name='login'),
    path('logout', views.log_out, name='logout'),
    path('register_owner', views.register_property_owner_user, name='register_property_owner_user'),
    path('register_contractor', views.register_contractor_user, name='register_contractor_user'),
    path('profile', views.profile, name='profile'),
    path('smithjones', views.smithjones, name='smithjones'),
]

adu_hack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('contractorPage/', TemplateView.as_view(template_name='index2.html'), name='index2'),
    path('accounts/', include('accounts.urls')),
    path('connections/', include('connections.urls')),
]

accounts/models.py
from django.db import models
from core.models import UUIDModel
from django.contrib.auth.models import AbstractUser


class InvalidUserType(BaseException):
    """Handle invalid user_type value
    """
    pass


class User(UUIDModel, AbstractUser):
    PROPERTY_OWNER = 0
    CONTRACTOR = 1
    STAFF = 2

    TYPE_CHOICES = (
        (PROPERTY_OWNER, 'Property Owner'),
        (CONTRACTOR, 'Contractor'),
        (STAFF, 'Staff'),
    )

    user_type = models.PositiveSmallIntegerField(
        choices=TYPE_CHOICES, default=0
    )
    contractor_information = models.OneToOneField(
        'accounts.ContractorInformation',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='user',
    )
    property_owner_information = models.OneToOneField(
        'accounts.PropertyOwnerInformation',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='user',
    )

    @property
    def information(self):
        """Determine which information should be returned to the user
        """
        if self.user_type == self.PROPERTY_OWNER:
            return self.property_owner_information
        elif self.user_type == self.CONTRACTOR:
            return self.contractor_information
        elif self.user_type == self.STAFF:
            return self
        else:
            raise InvalidUserType('Invalid user type!')

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'


class PropertyOwnerInformation(UUIDModel):
    reviews = models.ManyToManyField('connections.Review', blank=True)

    class Meta:
        verbose_name = 'Property Owner'
        verbose_name_plural = 'Property Owners'


class ContractorInformation(UUIDModel):
    services = models.ManyToManyField('connections.Service')
    reviews = models.ManyToManyField('connections.Review', blank=True)

    class Meta:
        verbose_name = 'Contractor'
        verbose_name_plural = 'Contractors'

accounts/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from accounts.models import User, PropertyOwnerInformation, ContractorInformation


def smithjones(request):
    return render(request, 'accounts/contractor-profile.html', {})

def register_property_owner_user(request):
    if request.method == 'POST':
        user = User()
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.set_password(request.POST.get('password1'))
        user.user_type = 0

        po = PropertyOwnerInformation()
        po.save()

        user.property_owner_information = po
        user.save()
        return HttpResponseRedirect('/')
    return render(request, 'accounts/register-owner.html', {})


def register_contractor_user(request):
    if request.method == 'POST':
        user = User()
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.set_password(request.POST.get('password1'))
        user.user_type = 1
        co = ContractorInformation()
        co.save()

        user.contractor_information = co
        user.save()
        return HttpResponseRedirect('/')
    return render(request, 'accounts/register-contractor.html', {})


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if request.POST.get('next', '/') == '':
            next = '/'
        else:
            next = request.POST.get('next', '/')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(next)
        else:
            return HttpResponse("There was an error with your login information")
    return render(request, 'accounts/login.html')


def log_out(request):
    logout(request)
    return HttpResponseRedirect('/')


@login_required
def profile(request):
    return render(request, 'accounts/profile.html', {})

templates/accounts/contractor-profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <header>
        <div>
            <h1>Smith Jones</h1>
            <div class="rating">
                <img src="{% static 'imgs/filled_star.svg' %}">
                <img src="{% static 'imgs/filled_star.svg' %}">
                <img src="{% static 'imgs/filled_star.svg' %}">
                <img src="{% static 'imgs/filled_star.svg' %}">
                <img src="{% static 'imgs/empty_star.svg' %}">
                <img src="{% static 'imgs/empty_star.svg' %}">
            </div>
            <ul class="skills">
                <li>Electrical</li>
                <li>Digging</li>
                <li>Foundation</li>
            </ul>
            <p>Smith Jones Bio... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunut aliquip ex ea commodo consequat. Olum dolore eu
                feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
                praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,
                cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam
                erat
                volutpat. Ut wisi enim ad minim veniam. suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
        </div>
        <div class="contractorContact">
            <a class="orangeBtn" href="#">Contact</a>
            <ul>
                <li>(112) 112- 1112</li>
                <li>smithjones@gmail.com</li>
                <li>03521 SW John St<br>
                    Portland, OR 97219
                </li>
            </ul>
        </div>
    </header>

    <section class="reviews">
        <h1>Reviews</h1>
        <ul>
            <li>
                <div class="previewHeader">
                    <div>
                        <a><h2>Sally Jane</h2></a>
                        <div class="rating">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/empty_star.svg' %}">
                            <img src="{% static 'imgs/empty_star.svg' %}">
                        </div>
                    </div>
                </div>
                <p>Smith Jones Bio... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor incididunut aliquip ex ea commodo consequat. Olum dolore eu
                    feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit</p>
            </li>
            <li>
                <div class="previewHeader">
                    <div>
                        <a><h2>Mike Hall</h2></a>
                        <div class="rating">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/empty_star.svg' %}">
                            <img src="{% static 'imgs/empty_star.svg' %}">
                        </div>
                    </div>
                </div>
                <p>Smith Jones Bio... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor incididunut aliquip ex ea commodo consequat. Olum dolore eu
                    feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit</p>
            </li>
            <li>
                <div class="previewHeader">
                    <div>
                        <a><h2>Phil Ham</h2></a>
                        <div class="rating">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/filled_star.svg' %}">
                            <img src="{% static 'imgs/empty_star.svg' %}">
                        </div>
                    </div>
                </div>
                <p>Smith Jones Bio... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor incididunut aliquip ex ea commodo consequat. Olum dolore eu
                    feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit</p>
            </li>
        </ul>
    </section>

{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="center">
        <section>
            <p>Please log in</p>
            <div>
                <form method="POST" action="{% url 'accounts:login' %}"
                      class="pure-form pure-form-aligned">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                    <div>
                        <input id="username" type="text" name="username"
                               placeholder="Username">
                    </div>

                    <div>
                        <input id="password" type="password" name="password"
                               placeholder="Password">
                    </div>

                    <input class="orangeBtn" type="submit" value="Log In">
                </form>

                <span>Don't have an account?<br> <a href="{% url 'accounts:register_property_owner_user' %}">sign up as home owner</a> or <a href="{% url 'accounts:register_contractor_user' %}">sign up as contractor</a></span>
            </div>
        </section>
    </div>

{% endblock content %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>User Profile:</h1>
    Username: {{ user.username }} <br>
    Full Name: {{ user.name }} <br>
    User Type: {{ user.get_user_type_display }} <br>

    {% if user.get_user_type_display == 'Property Owner' %}
        {% for j in user.information.jobs.all %}
            i
            <p>{{ j.completed }}</p>
            <p>{{ j.site.address }}</p>
            {% if j.contractor.name %}
                <p>{{ j.contractor.name }}</p>
            {% endif %}

            {% for s in j.services.all %}
                <div>
                    <div>
                        {{ s.name }}
                    </div>
                    <div>
                        {{ s.description }}
                    </div>
                </div>
            {% endfor %}

            <p>{{ j.completed }}</p>

        {% endfor %}
    {% endif %}
{% endblock content %}

templates/accounts/register-contractor.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <section class="loginWrap">
            <p>Contractor Registration:</p>
            <form action="{% url 'accounts:register_contractor_user' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'accounts/partials/_register_common.html' %}
                <input class="orangeBtn" type="submit">
            </form>
            <span>Already have an account? <a href="{% url 'accounts:login' %}">log in here</a></span>
        </section>
    </div>
{% endblock content %}

templates/accounts/register-owner.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <section class="loginWrap">
            <p>Owner Sign Up</p>
            <form action="{% url 'accounts:register_property_owner_user' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'accounts/partials/_register_common.html' %}
                <input class="orangeBtn" type="submit">
            </form>
            <span>Already have an account? <a href="{% url 'accounts:login' %}">log in here</a></span>
        </section>
    </div>

{% endblock content %}