accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.login_user, name='login'),
    path('logout', views.log_out, name='logout'),
    path('register_owner', views.register_property_owner_user, name='register_property_owner_user'),
    path('register_contractor', views.register_contractor_user, name='register_contractor_user'),
    path('profile', views.profile, name='profile'),
    path('smithjones', views.smithjones, name='smithjones'),
]

adu_hack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('contractorPage/', TemplateView.as_view(template_name='index2.html'), name='index2'),
    path('accounts/', include('accounts.urls')),
    path('connections/', include('connections.urls')),
]

connections/urls.py
from django.urls import path
from . import views

app_name = 'connections'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('searchCont/', views.searchTwo, name='searchTwo'),
    # path('results/', views.results, name='results'),
    # path('profile/', views.profile, name='profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADU Hack</title>
    <meta name="description" content="Description">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block stylesheets %}{% endblock stylesheets %}
</head>
<body>
{% include 'partials/_navbar.html' %}
{% block content %}{% endblock content %}
{% block scripts %}{% endblock scripts %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <section class="jumbo">
        <h1>ADU: Facilitating trust and community growth</h1>
        <form action="{% url 'connections:search' %}" method="post">
            {% csrf_token %}
            <input type="submit" name="q" value="Search for contractors...">
        </form>
        <p>Contractor? &nbsp;&nbsp;<a href="#">Login Here</a></p>
    </section>
    <section class="works">
        <ul>
            <li>
                <div class="aboutImg"></div>
                <p>Search top qualified contractors with experience delivering the services that you need to complete
                    your project.</p>
            </li>
            <li>
                <div class="aboutImg"></div>
                <p>Let us do the heavy lifting! Create a job posting with the description and qualifications needed to get the job done. We
                will post it to the best qualified contractors to connect to get the job done.</p>
            </li>
            <li>
                <div class="aboutImg"></div>
                <p>When you and your selected contractor are ready,
                    we setup and manage an escrow account with your contractor
                    so that you can feel confident in the job being done well.
                </p>
            </li>
        </ul>
    </section>
{% endblock content %}

templates/index2.html
{% extends 'base.html' %}

{% block content %}
    <section class="jumbo">
        <h1>ADU: Facilitating trust and community growth</h1>
        <form action="{% url 'connections:searchTwo' %}" method="GET">
            <input type="text" name="q" placeholder="Search for jobs...">
        </form>
        {% if not user.is_authenticated %}
            <p>Homeowner? &nbsp;&nbsp;<a href="#">Login Here</a></p>
        {% endif %}
    </section>
    <section class="works">
        <ul>
            <li>
                <div class="aboutImg"></div>
                <p>Search top qualified contractors with experience delivering the services that you need to complete
                    your project.</p>
            </li>
            <li>
                <div class="aboutImg"></div>
                <p>Let us do the heavy lifting! Create a job posting with the description and qualifications needed to
                    get the job done. We
                    will post it to the best qualified contractors to connect to get the job done.</p>
            </li>
            <li>
                <div class="aboutImg"></div>
                <p>When you and your selected contractor are ready,
                    we setup and manage an escrow account with your contractor
                    so that you can feel confident in the job being done well.
                </p>
            </li>
        </ul>
    </section>
{% endblock content %}