accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.login_user, name='login'),
    path('logout', views.log_out, name='logout'),
    path('register_owner', views.register_property_owner_user, name='register_property_owner_user'),
    path('register_contractor', views.register_contractor_user, name='register_contractor_user'),
    path('profile', views.profile, name='profile'),
    path('smithjones', views.smithjones, name='smithjones'),
]

adu_hack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('contractorPage/', TemplateView.as_view(template_name='index2.html'), name='index2'),
    path('accounts/', include('accounts.urls')),
    path('connections/', include('connections.urls')),
]

connections/urls.py
from django.urls import path
from . import views

app_name = 'connections'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('searchCont/', views.searchTwo, name='searchTwo'),
    # path('results/', views.results, name='results'),
    # path('profile/', views.profile, name='profile'),
]

connections/models.py
from django.db import models
from core.models import UUIDModel, GeoLocationModel


class Site(UUIDModel, GeoLocationModel):
    """Work site model, contains geocoded coords and address
    """
    def __str__(self):
        return self.address


class Service(UUIDModel):
    name = models.CharField(max_length=256, unique=True)
    description = models.TextField()

    @staticmethod
    def top_5():
        return Service.objects.all()[:5]

    def __str__(self):
        return self.name


class Job(UUIDModel):
    completed = models.BooleanField(default=False)

    site = models.OneToOneField(Site, on_delete=models.CASCADE)
    property_owner = models.ForeignKey(
        'accounts.PropertyOwnerInformation',
        on_delete=models.CASCADE,
        related_name='jobs'
    )
    contractor = models.ForeignKey(
        'accounts.ContractorInformation', on_delete=models.CASCADE, blank=True, null=True)
    services = models.ManyToManyField(Service, blank=True)
    description = models.TextField()


class Review(UUIDModel):
    rating = models.PositiveSmallIntegerField(null=True, blank=True)
    description = models.TextField()
    contractor = models.OneToOneField(
        'accounts.ContractorInformation', on_delete=models.CASCADE)
    job = models.OneToOneField(Job, on_delete=models.CASCADE)

connections/forms.py
from django import forms


class JobForm(forms.Form):
    address = forms.CharField(label='Address', max_length=512, required=True)
    description = forms.CharField(label='Description', max_length=100, required=True)

connections/views.py
from django.shortcuts import render

from accounts.models import User
from accounts.models import ContractorInformation
from connections.models import Service


def search(request):
    if request.user.is_authenticated and request.user.user_type == 0:
        jobs = request.user.information.jobs.filter(completed=False)

    contractors = User.objects.filter(user_type=User.CONTRACTOR)
    popular_services = Service.top_5()

    print(contractors)

    return render(request, 'connections/search.html', {
        'services': popular_services,
        'contractors': contractors,
    })


def searchTwo(request):
    return render(request, 'connections/search2.html')

templates/connections/jobForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADU: Job Form</title>
</head>
<body>
<h1>Create A Job</h1>
<form action="{% url 'connections:createJob' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <ul>
        {% for service in services %}
        <li><input type="checkbox" name="service_box" value="{{ service.name }}">{{ service.name }}</li>
        {% endfor %}
    </ul>
    <input type="submit" value="Submit"/>
</form>
</body>
</html>

templates/connections/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="mainContent listPage">
        <aside class="sidebar">
            <div class="services">
                <h2 class="expand">Filter Services</h2>
                <ul>
                    {% for service in services %}
                        <li><input type="checkbox" value="{{ service.name }}">{{ service.name }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div>
                <h2 class="expand">Filter Stars</h2>
                <ul class="stars">
                    <li><input type="checkbox" name="fiveStar"></li>
                    <li><input type="checkbox" name="fourStar"></li>
                    <li><input type="checkbox" name="threeStar"></li>
                    <li><input type="checkbox" name="twoStar"></li>
                    <li><input type="checkbox" name="oneStar"></li>
                </ul>
            </div>
        </aside>

        <section class="mainList">
            <p class="smallText">{{ contractors.count }} search results</p>
            <ul>
                {% for contractor in contractors %}
                    <li>
                        <div class="previewHeader">
                            <div>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'accounts:smithjones' %}">
                                        <h2>{{ contractor.name }}</h2>
                                    </a>
                                {% else %}

                                    <h2>{{ contractor.name }}</h2>
                                {% endif %}
                                <div class="rating">
                                    <img src="{% static 'imgs/filled_star.svg' %}">
                                    <img src="{% static 'imgs/filled_star.svg' %}">
                                    <img src="{% static 'imgs/filled_star.svg' %}">
                                    <img src="{% static 'imgs/filled_star.svg' %}">
                                    <img src="{% static 'imgs/empty_star.svg' %}">
                                    <img src="{% static 'imgs/empty_star.svg' %}">
                                </div>
                            </div>
                            {% if user.is_authenticated %}
                                <a class="orangeBtn" href="#">Contact</a>
                            {% else %}
                                <a class="orangeBtn" href="{% url 'accounts:login' %}">Login for more info</a>
                            {% endif %}
                        </div>
                        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunut
                            aliquip
                            ex ea commodo consequat...</p>
                    </li>
                {% endfor %}
            </ul>
        </section>

    </div>
{% endblock content %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>

    <script>
        $('.expand').click(function () {
            $(this).next().slideToggle(250)
            $(this).toggleClass('closed')
        });
    </script>
{% endblock scripts %}

templates/connections/search2.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="mainContent listPage">
        <aside class="sidebar">
            <div class="services">
                <h2 class="expand">Filter Services</h2>
                <ul>
                    <li><input type="checkbox" value="Electrical">Electrical</li>
                    <li><input type="checkbox" value="Landscaping">Landscaping</li>
                    <li><input type="checkbox" value="Masonry">Masonry</li>
                    <li><input type="checkbox" value="Demolition">Demolition</li>
                </ul>
            </div>
            <div>
                <h2 class="expand">Filter Max Miles</h2>
                <ul>
                    <li><input type="checkbox" name="five">5 miles</li>
                    <li><input type="checkbox" name="ten">10 miles</li>
                    <li><input type="checkbox" name="twentyfive">25 miles</li>
                    <li><input type="checkbox" name="any">Any</li>
                </ul>
            </div>
        </aside>

        <section class="mainList">
            <p class="smallText">2 search results</p>
            <ul class="contract">
                <li>
                    <div class="previewHeader">
                        <div>
                            <a>
                                <h2>3025 SW Cedar Hills Blvd, Beaverton, OR 97005</h2>
                            </a>
                            <div class="medText rating">
                                16.4 miles away
                            </div>
                        </div>
                        {% if user.is_authenticated %}
                            <a class="orangeBtn" href="#">Contact</a>
                        {% else %}
                            <a class="orangeBtn" href="{% url 'accounts:login' %}">Login for more info</a>
                        {% endif %}
                    </div>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunut
                        aliquip
                        ex ea commodo consequat...</p>
                </li>
                <li>
                    <div class="previewHeader">
                        <div>
                            <a>
                                <h2>15901 SW Jenkins Rd, Aloha, OR 97006</h2>
                            </a>
                            <div class="medText rating">
                                10.2 miles away
                            </div>
                        </div>
                        {% if user.is_authenticated %}
                            <a class="orangeBtn" href="#">Contact</a>
                        {% else %}
                            <a class="orangeBtn" href="{% url 'accounts:login' %}">Login for more info</a>
                        {% endif %}
                    </div>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunut
                        aliquip
                        ex ea commodo consequat...</p>
                </li>
            </ul>
        </section>

    </div>
{% endblock content %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>

    <script>
        $('.expand').click(function () {
            $(this).next().slideToggle(250)
            $(this).toggleClass('closed')
        });
    </script>
{% endblock scripts %}